input_channel: 3

depth_multiple: 0.5
width_multiple: 1.0

##input_channels: int, kernel: int, expanded_channels: int, out_channels: int, use_se: bool,activation: str, stride: int, dilation: int, width_mult: float)
backbone:
    # [repeat, module, args]
    [
        # Conv argument: [out_channel, kernel_size, stride, padding_size]
        # if padding_size is not given or null, the padding_size will be auto adjusted as padding='SAME' in TensorFlow
        [3, DWConv, [48, 3, 1, null, "ReLU"]],
        [4, Conv, [32, 3, 1, null, 1, "ReLU"]],
        [3, Conv, [112, 3, 2, null, 1, "ReLU"]],
        [5, InvertedResidualv3, [3, 3, 32 ,0, 0,1]],
        [3, DWConv, [224, 3, 2, null, "Hardswish"]],
        [3, Conv, [64, 6, 1, null, 1, "Hardswish"]],
        [1, InvertedResidualv3, [5, 2.4, 8 , 0, 1,2]],
        [1, Conv, [1024, 1, 1]],
        [1, GlobalAvgPool, []],
 
        [1, FixedConv, [6,1,1, null,1, null]]
    ]
