input_channel: 3

depth_multiple: 0.5
width_multiple: 0.75

##input_channels: int, kernel: int, expanded_channels: int, out_channels: int, use_se: bool,activation: str, stride: int, dilation: int, width_mult: float)
backbone:
    # [repeat, module, args]
    [
        # Conv argument: [out_channel, kernel_size, stride, padding_size]
        # if padding_size is not given or null, the padding_size will be auto adjusted as padding='SAME' in TensorFlow
        [3, DWConv, [64, 3, 2, null, "Hardswish"]],
        [2, DWConv, [64, 1, 1, null, "ReLU"]],
        [5, DWConv, [96, 3, 1, null, "ReLU"]],
        [1, DWConv, [240, 5, 2, null, "ReLU"]],
        # k t c SE HS s
        #oup, stride, expand_ratio, norm_layer=None)
        [1, Conv, [192, 3, 2, null, 1, "ReLU"]],
        [2, InvertedResidualv2, [48, 6, 2]],
        [1, GlobalAvgPool, []],
        [1, Conv, [1024, 1, 1]],
        [1, FixedConv, [6,1,1, null,1, null]]
    ]
