input_channel: 3

depth_multiple: 1.0
width_multiple: 1.0

##input_channels: int, kernel: int, expanded_channels: int, out_channels: int, use_se: bool,activation: str, stride: int, dilation: int, width_mult: float)
backbone:
    # [repeat, module, args]
    [
        # Conv argument: [out_channel, kernel_size, stride, padding_size]
        # if padding_size is not given or null, the padding_size will be auto adjusted as padding='SAME' in TensorFlow
        [2, Conv, [48, 3, 2, null, 1, "Hardswish"]],
        [1, InvertedResidualv2, [16, 1, 2]],
        [4, InvertedResidualv2, [24, 4, 1]],
        # k t c SE HS s
        #oup, stride, expand_ratio, norm_layer=None)
        [1, Conv, [416, 5, 2, null, 1, "Hardswish"]],
        [2, DWConv, [768, 1, 2, null, "ReLU"]],
        [1, GlobalAvgPool, []],
        [1, Conv, [256, 1, 1]],
        [1, FixedConv, [6,1,1, null,1, null]]
    ]
