wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.7
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1637819455
    t:
      1:
      - 5
      2:
      - 5
      4: 3.7.11
      5: 0.12.7
      8:
      - 5
direction:
  desc: null
  value: MINIMIZE
